steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - hello_word
      - --region=europe-central2
      - --source=.
      - --trigger-http
      - --runtime=python311
      - --memory=128MB
      - --timeout=90
      - --min-instances=1
      - --max-instances=1
      - --security-level=secure-always
      - --ingress-settings=all
      - --no-allow-unauthenticated
      - --service-account=hello-word-functions-sa@evocative-hour-398618.iam.gserviceaccount.com